src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isRead;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->isRead;
    }

    public function setIsRead(bool $isRead): self
    {
        $this->isRead = $isRead;

        return $this;
    }
}

templates/base.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="La Boutique qui vend des articles pour fabriquer des cocktails">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>{% block title %} H2o Fabrik Cocktail{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('assets/css/h2oFabrikCocktail.css') }}">
    {% block javascript %}
    {% endblock %}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" aria-label="Fifth navbar example">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{  path('home') }}">H2o Fabrik Cocktail</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="dropdown05" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ asset('assets/img/bouteilles-de-vin.png') }} " alt="icons 3 bouteilles" class="cart-icon">
                            Produits
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown05">
                            <li><a class="dropdown-item" href="{{ path('products') }}">Nos Produits</a></li>
                            <li><a class="dropdown-item" href="{{ path('my_bar') }}">Mon Bar</a></li>
                            <li><a class="dropdown-item" href="{{ path('shopping_list') }}">Liste de courses</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{  path('blogposts') }}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ path('contact') }}">Contact</a>
                    </li>
                </ul>
                <div class="navbar-item-custom">
                    {% if app.user %}
                        <a href="{{ path('account') }}">Mon compte <small>*{{ app.user.firstname }}*</small></a> | <a href="{{ path('app_logout') }}">Déconnexion</a>
                    {% else %}
                        <a href="{{ path('app_login')  }}">Connexion</a> | <a href="{{ path('register') }}">Inscription</a>
                    {% endif %}
                </div>
                <a href="{{ path('cart') }}">
                    <img src="{{ asset('assets/img/panier.png') }}" alt="Mon panier" class="cart-icon">
                </a>
            </div>
            </div>
        </div>
    </nav>

</header>

<main role="main">
    {% if block('video') is defined %}

        <div class="tm-hero d-flex justify-content-center align-items-center">
            <video autoplay muted>
                <source src="https://storage.coverr.co/videos/l2WwnIrEa1E7gpqaAymAt02AdHUWK2Mjo?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6Ijg3NjdFMzIzRjlGQzEzN0E4QTAyIiwiaWF0IjoxNjM2MDI2Mjg4fQ.VUDMHh4gEjBOlIv0Z9pqLrPzG1sgpmKEb4YJiDvEYSY"></source>
            </video>

            <form class="d-flex position-absolute">
                <!--*******ALPHABET PALETTE*******-->
                <div class="container-fluid m-5">
                    <h1 id="titleHome" class="text-center font-weight-bold text-secondary">H2o Fabrik Cocktail</h1>
                    </br>
                    <h5 id="instructions" class="text-center text-info font-weight-bold">Pour des idées de cocktail aller sur la lettre de votre choix</h5>
                    <div class="row mt-1">
                        <div id="letter" class="col text-wrap text-sm-center">
                            <div class="btn-group flex-wrap" id="alphabetGroup" role="group">
                                <button class="btn btn-info" onclick="letterPagination('a')"
                                        type="button" >A
                                </button>
                                <button class="btn btn-info" id="btnB" onclick="letterPagination('b')"
                                        type="button">B
                                </button>
                                <button class="btn btn-info" id="btnC" onclick="letterPagination('c')"
                                        type="button">C
                                </button>
                                <button class="btn btn-info" id="btnD" onclick="letterPagination('d')"
                                        type="button">D
                                </button>
                                <button class="btn btn-info" id="btnE" onclick="letterPagination('e')"
                                        type="button">E
                                </button>
                                <button class="btn btn-info" id="btnF" onclick="letterPagination('f')"
                                        type="button">F
                                </button>
                                <button class="btn btn-info" id="btnG" onclick="letterPagination('g')"
                                        type="button">G
                                </button>
                                <button class="btn btn-info" id="btnH" onclick="letterPagination('h')"
                                        type="button">H
                                </button>
                                <button class="btn btn-info" id="btnI" onclick="letterPagination('i')"
                                        type="button">I
                                </button>
                                <button class="btn btn-info" id="btnJ" onclick="letterPagination('j')"
                                        type="button">J
                                </button>
                                <button class="btn btn-info" id="btnK" onclick="letterPagination('k')"
                                        type="button">K
                                </button>
                                <button class="btn btn-info" id="btnL" onclick="letterPagination('l')"
                                        type="button">L
                                </button>
                                <button class="btn btn-info" id="btnM" onclick="letterPagination('m')"
                                        type="button">M
                                </button>
                                <button class="btn btn-info" id="btnN" onclick="letterPagination('n')"
                                        type="button">N
                                </button>
                                <button class="btn btn-info" id="btnO" onclick="letterPagination('o')"
                                        type="button">O
                                </button>
                                <button class="btn btn-info" id="btnP" onclick="letterPagination('p')"
                                        type="button">P
                                </button>
                                <button class="btn btn-info" id="btnQ" onclick="letterPagination('q')"
                                        type="button">Q
                                </button>
                                <button class="btn btn-info" id="btnR" onclick="letterPagination('r')"
                                        type="button">R
                                </button>
                                <button class="btn btn-info" id="btnS" onclick="letterPagination('s')"
                                        type="button">S
                                </button>
                                <button class="btn btn-info" id="btnT" onclick="letterPagination('t')"
                                        type="button">T
                                </button>
                                <button class="btn btn-info" id="btnU" onclick="letterPagination('u')"
                                        type="button">U
                                </button>
                                <button class="btn btn-info" id="btnV" onclick="letterPagination('v')"
                                        type="button">V
                                </button>
                                <button class="btn btn-info" id="btnW" onclick="letterPagination('w')"
                                        type="button">W
                                </button>
                                <button class="btn btn-info" id="btnX" onclick="letterPagination('x')"
                                        type="button">X
                                </button>
                                <button class="btn btn-info" id="btnY" onclick="letterPagination('y')"
                                        type="button">Y
                                </button>
                                <button class="btn btn-info" id="btnZ" onclick="letterPagination('z')"
                                        type="button">Z
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <!--*******RESULTS*******-->
        <section id="results">
            <div class="container-fluid">
                <div class="row align-items-start" id="data"></div>
            </div>

        </section>

        <!--*******MODAL DETAILS*******-->
        <div aria-hidden="true" class="modal fade"
             id="modalDetails" role="dialog"
             tabindex="-1">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header" id="modal-cocktail-header">
                    </div>
                    <div class="modal-body" id="modal-cocktail">
                    </div>
                </div>
            </div>
        </div>




    {% endif %}

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing {% if block('video') is not defined %}mt-5{% endif %}">

        {% block content %}
        {% endblock %}

    </div><!-- /.container -->

    <!-- FOOTER -->
<footer class="footer-custom bg-dark">
    <p class="text-white">
        &copy; 2021-2022 H2o Fabrik Cocktail <br>
        <small> Pauline Marot<br>
    </p>
</footer>
</main>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="{{ asset('assets/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/API/cocktail.js') }}"></script>

</body>
{% block script %}
{% endblock %}
</html>